name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Ant Foody
        run: ant -noinput -buildfile Foody/build.xml
      - name: Build with Ant FoodyOrder
        run: ant -noinput -buildfile Foody/build.xml
